apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwwtaggerdep2
  namespace: cms-ml-hvv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwwtagger
  template:
    metadata:
      labels:
        app: hwwtagger
    spec:
      containers:
      - name: container
        image: gitlab-registry.nrp-nautilus.io/raghsthebest/hww-tagger:latest
        command: ["/bin/bash", "-c", "sleep infinity"]
        resources:
          limits:
            cpu: "4"
            memory: 20Gi
          requests:
            memory: 16Gi
            cpu: "4"
          #  nvidia.com/gpu: "1"
            ephemeral-storage: 512Gi
        volumeMounts:
        - mountPath: /hwwtaggervol
          name: hwwtaggervol
      volumes:
        - name: hwwtaggervol
          persistentVolumeClaim:
            claimName: hwwtaggervol


# apiVersion: v1
# kind: Pod
# metadata:
#   name: hwwtaggerpod
#   labels:
#     app: hwwtagger
# spec:
#   containers:
#   - name: container
#     image: gitlab-registry.nrp-nautilus.io/raghsthebest/hww-tagger:latest
#     command: ["/bin/bash", "-c", "sleep infinity"]
#     resources:
#       requests:
#         memory: 5Gi
#         cpu: "2"
#       #  nvidia.com/gpu: "1"
#         ephemeral-storage: 512Gi
#     volumeMounts:
#     - mountPath: /hwwtaggervol
#       name: hwwtaggervol
#   restartPolicy: Never
#   volumes:
#     - name: hwwtaggervol
#       persistentVolumeClaim:
#         claimName: hwwtaggervol
