apiVersion: v1
kind: Pod
metadata:
  name: hwwtaggerpod
  labels:
    app: hwwtagger
spec:
  containers:
  - name: container
    image: gitlab-registry.nrp-nautilus.io/raghsthebest/hww-tagger:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      requests:
        memory: 4Gi
        cpu: "2"
      #  nvidia.com/gpu: "1"
        ephemeral-storage: 512Gi
    volumeMounts:
    - mountPath: /hwwtaggervol
      name: hwwtaggervol
  restartPolicy: Never
  volumes:
    - name: hwwtaggervol
      persistentVolumeClaim:
        claimName: hwwtaggervol
