apiVersion: v1
kind: Pod
metadata:
  name: volcppod
  labels:
    app: hwwtagger
spec:
  containers:
  - name: container
    image: python:3
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      requests:
        memory: 4Gi
        cpu: "1"
      #  nvidia.com/gpu: "1"
        ephemeral-storage: 32Gi
    volumeMounts:
    - mountPath: /hwwtaggervol
      name: hwwtaggervol
  restartPolicy: Never
  volumes:
    - name: hwwtaggervol
      persistentVolumeClaim:
        claimName: hwwtaggervol
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - prp-gpu-2.t2.ucsd.edu
