apiVersion: batch/v1
kind: Job
metadata:
  name: melissahwwjob-1lepvqcd-inference-6sig-6may
  labels:
    app: weavertagger
spec:
  template:
    spec:
      containers:
      - name: container
        image: gitlab-registry.nrp-nautilus.io/raghsthebest/hww-tagger:latest
        command:
        - "/bin/bash"
        - "-c"
        - >
          git -C /hwwtaggervol/melissa-weaver pull &&
          mkdir -p /hwwtaggervol/inferences/mq/4may-1lepvqcd &&
          mkdir -p /hwwtaggervol/plots/mq/4may-1lepvqcd &&
          mkdir -p /hwwtaggervol/models/mq/4may-1lepvqcd &&
          cd /opt/repo/weaver &&
          (python -u train.py
          --predict
          --predict-output /hwwtaggervol/inferences/mq/4may-1lepvqcd/qcd.root
          --data-test '/hwwtaggervol/training/ak8_Mar29/test//QCD*/*.root'
          --data-config /hwwtaggervol/melissa-weaver/data/mq_ntuples/melissa_dataconfig_semilep_QCD.yaml
          --network-config networks/particle_net_pf_sv_4_layers_pyg_ef.py
          --model-prefix /hwwtaggervol/models/mq/05_02_ak8mod/05_02_ak8mod_best_epoch_state.pt
          --gpus "0,1"
          --batch-size 256
          --fetch-step 0.02
          --num-workers 2
          | tee -a /hwwtaggervol/inferences/mq/4may-1lepvqcd/log_qcd.txt) && 
          (python -u train.py
          --predict
          --predict-output /hwwtaggervol/inferences/mq/4may-1lepvqcd/bulkg.root
          --data-test '/hwwtaggervol/training/ak8_Mar29/test/Bulk*/*.root'
          --data-config /hwwtaggervol/melissa-weaver/data/mq_ntuples/melissa_dataconfig_semilep_QCD.yaml
          --network-config networks/particle_net_pf_sv_4_layers_pyg_ef.py
          --model-prefix /hwwtaggervol/models/mq/05_02_ak8mod/05_02_ak8mod_best_epoch_state.pt
          --gpus "0,1"
          --batch-size 256
          --fetch-step 0.02
          --num-workers 2
          | tee -a /hwwtaggervol/inferences/mq/4may-1lepvqcd/log_bulkg.txt) && 
          pip install coffea mplhep --upgrade &&
          (python -u train.py
          --predict
          --predict-output /hwwtaggervol/inferences/mq/4may-1lepvqcd/hwwlnuqq.root
          --data-test '/hwwtaggervol/training/ak8_Apr14/test/GluGluHToWWToLNuQQ*/*.root'
          --data-config /hwwtaggervol/melissa-weaver/data/mq_ntuples/melissa_dataconfig_semilep_QCD.yaml
          --network-config networks/particle_net_pf_sv_4_layers_pyg_ef.py
          --model-prefix /hwwtaggervol/models/mq/05_02_ak8mod/05_02_ak8mod_best_epoch_state.pt
          --gpus "0,1"
          --batch-size 256
          --fetch-step 0.02
          --num-workers 2
          | tee -a /hwwtaggervol/inferences/mq/4may-1lepvqcd/log_lnuqq.txt) && 
          (python -u plots/plot_classification_fromoutput.py
          --name ParticleNet-PyG-EF
          --ifile /hwwtaggervol/inferences/mq/4may-1lepvqcd/qcd.root
          --odir /hwwtaggervol/plots/mq/4may-1lepvqcd/
          --signals hww_elenuqq_merged, hww_elenuqq_semimerged, hww_munuqq_merged, hww_munuqq_semimerged, hww_taunuqq_merged, hww_taunuqq_semimerged,
          --bkgs qcd1lep,qcd1lep,qcd1lep,qcd1lep,qcd1lep,qcd1lep
          --mbranch fj_genRes_mass
          --jet AK8
          -v
          --isig /hwwtaggervol/inferences/mq/4may-1lepvqcd/bulkg.root,/hwwtaggervol/inferences/mq/4may-1lepvqcd/hwwlnuqq.root
          --isignames BulkGSMHiggs,SMHiggs
          | tee -a /hwwtaggervol/plots/mq/4may-1lepvqcd/log.txt) &&
          (python -u plots/plot_losses.py
          --model-path /hwwtaggervol/models/mq/05_02_ak8mod/05_02_ak8mod
          --output /hwwtaggervol/plots/mq/4may-1lepvqcd/losses.png
          | tee -a /hwwtaggervol/plots/mq/4may-1lepvqcd/log.txt)
        volumeMounts:
        - mountPath: /hwwtaggervol
          name: hwwtaggervol
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: 40Gi
            cpu: "8"
            nvidia.com/gpu: "2"
          requests:
            memory: 32Gi
            cpu: "6"
            nvidia.com/gpu: "2"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - --single-branch
          - https://github.com/quinnanm/weaver
          - /opt/repo/weaver
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: hwwtaggervol
        persistentVolumeClaim:
          claimName: hwwtaggervol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-GTX-1080
                - NVIDIA-GeForce-GTX-1080-Ti
                - NVIDIA-GeForce-GTX-2080-Ti
      restartPolicy: Never
  backoffLimit: 0
