apiVersion: batch/v1
kind: Job
metadata:
  name: mq-misc
  labels:
    app: weavertagger
spec:
  template:
    spec:
      containers:
      - name: container
        image: gitlab-registry.nrp-nautilus.io/raghsthebest/hww-tagger:latest
        command:
        - "/bin/bash"
        - "-c"
        - >
          git -C /hwwtaggervol/melissa-weaver pull &&
          sudo apt-get install rsync
        volumeMounts:
        - mountPath: /hwwtaggervol
          name: hwwtaggervol
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: 40Gi
            cpu: "8"
            nvidia.com/gpu: "2"
          requests:
            memory: 32Gi
            cpu: "6"
            nvidia.com/gpu: "2"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - --single-branch
          - https://github.com/quinnanm/weaver
          - /opt/repo/weaver
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: hwwtaggervol
        persistentVolumeClaim:
          claimName: hwwtaggervol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-GTX-1080
                - NVIDIA-GeForce-GTX-1080-Ti
                - NVIDIA-GeForce-GTX-2080-Ti
      restartPolicy: Never
  backoffLimit: 0
