# samples: 4q & QCD
# sample type: standard model
# reweight_method: flat

apiVersion: batch/v1
kind: Job
metadata:
  name: weaver-rk-inference-4-layers
  labels:
    app: hwwtaggervol
spec:
  template:
    spec:
      containers:
      - name: container
        image: gitlab-registry.nrp-nautilus.io/raghsthebest/hww-tagger/weaver
        command:
        - "/bin/bash"
        - "-c"
        - >
          git clone https://github.com/rkansal47/weaver &&
          cd weaver &&
          git fetch &&
          mkdir -p /hwwtaggervol/inferences/rk/ /hwwtaggervol/plots/rk/ak15_smsamples_4_layer_hh4v &&
          (python -u train.py
          --predict
          --predict-output /hwwtaggervol/inferences/rk/ak15_smsamples_4_layer_hh4v.root
          --data-test '/hwwtaggervol/training/ak15_Jul27/*/*HHTo4V*/*.root' '/hwwtaggervol/training/ak15_Jul27/test/QCD*/*.root'
          --data-config data/ak15hww_points_pf_sv_pt_decorr.yaml
          --network-config networks/particle_net_pf_sv_4_layers.py
          --model-prefix /hwwtaggervol/models/rk/imperium_models/ak15_v04_hwwvsQCD_nworkers3_bsize256_fstep0p02_lr3em3_4_layers_best_epoch_state.pt
          --gpus "0"
          --batch-size 16
          --fetch-step 0.02
          | tee /hwwtaggervol/inferences/rk/ak15_smsamples_4_layer_hh4v.txt) &&
          pip install coffea mplhep --upgrade &&
          (python -u plot_classification_fromoutput.py
          --name "smsamples_4_layer"
          --ifile /hwwtaggervol/inferences/rk/ak15_smsamples_4_layer_hh4v.root
          --odir /hwwtaggervol/plots/rk/ak15_smsamples_4_layer_hh4v
          --signals hww_4q,hww_munuqq,hww_elenuqq
          --bkgs qcd_old,qcd_old,qcd_old
          | tee /hwwtaggervol/plots/rk/ak15_smsamples_4_layer_hh4v/log.txt &
          wait)
        volumeMounts:
        - mountPath: /hwwtaggervol
          name: hwwtaggervol
        resources:
          limits:
            memory: 40Gi
            cpu: "4"
            nvidia.com/gpu: "1"
          requests:
            memory: 40Gi
            cpu: "2"
            nvidia.com/gpu: "1"
      volumes:
      - name: hwwtaggervol
        persistentVolumeClaim:
          claimName: hwwtaggervol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In
                values:
                - "1080"
                - 1080Ti
                - 2080Ti
      restartPolicy: Never
  backoffLimit: 0
